// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/resources": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/resources/:id": {
    params: {
      "id": string;
    };
  };
  "/resources/:id/report": {
    params: {
      "id": string;
    };
  };
  "/resources/new": {
    params: {};
  };
  "/auth/muid": {
    params: {};
  };
  "/favorite": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/profile/resources": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/sorts": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/resources" | "/auth/callback" | "/resources/:id" | "/resources/:id/report" | "/resources/new" | "/auth/muid" | "/favorite" | "/profile" | "/profile/resources" | "/logout" | "/search" | "/about" | "/admin" | "/admin/sorts" | "/login";
  };
  "routes/resources._index/route.tsx": {
    id: "routes/resources._index";
    page: "/resources";
  };
  "routes/auth.callback.ts": {
    id: "routes/auth.callback";
    page: "/auth/callback";
  };
  "routes/resources.$id/route.tsx": {
    id: "routes/resources.$id";
    page: "/resources/:id" | "/resources/:id/report";
  };
  "routes/resources.$id.report/route.tsx": {
    id: "routes/resources.$id.report";
    page: "/resources/:id/report";
  };
  "routes/resources.new/route.tsx": {
    id: "routes/resources.new";
    page: "/resources/new";
  };
  "routes/auth.muid.ts": {
    id: "routes/auth.muid";
    page: "/auth/muid";
  };
  "routes/favorite/route.tsx": {
    id: "routes/favorite";
    page: "/favorite";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile" | "/profile/resources";
  };
  "routes/profile.resources/route.tsx": {
    id: "routes/profile.resources";
    page: "/profile/resources";
  };
  "routes/profile._index/route.tsx": {
    id: "routes/profile._index";
    page: "/profile";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/search/route.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin" | "/admin/sorts";
  };
  "routes/admin._index.tsx": {
    id: "routes/admin._index";
    page: "/admin";
  };
  "routes/admin.sorts/route.tsx": {
    id: "routes/admin.sorts";
    page: "/admin/sorts";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/login._index/route.tsx": {
    id: "routes/login._index";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/resources._index": typeof import("./app/routes/resources._index/route.tsx");
  "routes/auth.callback": typeof import("./app/routes/auth.callback.ts");
  "routes/resources.$id": typeof import("./app/routes/resources.$id/route.tsx");
  "routes/resources.$id.report": typeof import("./app/routes/resources.$id.report/route.tsx");
  "routes/resources.new": typeof import("./app/routes/resources.new/route.tsx");
  "routes/auth.muid": typeof import("./app/routes/auth.muid.ts");
  "routes/favorite": typeof import("./app/routes/favorite/route.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/profile.resources": typeof import("./app/routes/profile.resources/route.tsx");
  "routes/profile._index": typeof import("./app/routes/profile._index/route.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/search": typeof import("./app/routes/search/route.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin._index": typeof import("./app/routes/admin._index.tsx");
  "routes/admin.sorts": typeof import("./app/routes/admin.sorts/route.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/login._index": typeof import("./app/routes/login._index/route.tsx");
};